"""HammerDB TPC-C schema reference and post-deploy validation thresholds."""

from __future__ import annotations

# HammerDB builds the standard TPC-C OLTP schema (production-like, multi-table).
# With DR_VALIDATION_HAMMERDB_WAREHOUSES=1 (default), buildschema loads fixed counts.
TPCC_TABLES: dict[str, str] = {
    "warehouse": "Distribution centers (w_id primary key)",
    "district": "Regional districts within each warehouse (d_id, d_w_id)",
    "customer": (
        "Customer records with numeric IDs and name/contact fields "
        "(c_id, c_first, c_middle, c_last, c_phone, c_balance, …)"
    ),
    "stock": "Inventory per warehouse and item (s_i_id, s_w_id, s_quantity, …)",
    "item": "Product catalog shared across warehouses (i_id, i_name, i_price, …)",
    "orders": "Customer orders (o_id, o_c_id, o_d_id, o_w_id, o_entry_d, …)",
    "order_line": "Line items for each order (ol_o_id, ol_d_id, ol_i_id, …)",
    "new_order": "Pending orders queue (no_o_id, no_d_id, no_w_id)",
    "history": "Payment history rows generated by HammerDB transactions",
}

TPCC_TABLE_NAMES: tuple[str, ...] = tuple(TPCC_TABLES)

# Minimum row counts after HammerDB buildschema with one warehouse.
TPCC_MIN_ROW_COUNTS: dict[str, int] = {
    "warehouse": 1,
    "district": 10,
    "customer": 3000,
    "stock": 100_000,
    "item": 100_000,
    "orders": 0,  # grows under autopilot load
    "order_line": 0,
    "new_order": 0,
    "history": 0,
}

# Fixed buildschema tables (exact COUNT(*) is cheap). Mutable OLTP tables grow under
# autopilot and are counted via planner statistics during DR snapshots.
TPCC_STATIC_TABLES: tuple[str, ...] = tuple(
    name for name, minimum in TPCC_MIN_ROW_COUNTS.items() if minimum > 0
)
TPCC_MUTABLE_TABLES: tuple[str, ...] = tuple(
    name for name, minimum in TPCC_MIN_ROW_COUNTS.items() if minimum == 0
)

AUDIT_TABLE = "dr_validation_audit"
AUDIT_TABLE_DESCRIPTION = (
    "DR validation audit trail (seq primary key, committed_at UTC, hostname, source)"
)


def validate_tpcc_populated(tpcc_counts: dict[str, int]) -> list[str]:
    """Return errors when required TPC-C tables are missing or under minimum row counts."""
    errors: list[str] = []
    for table, minimum in TPCC_MIN_ROW_COUNTS.items():
        count = tpcc_counts.get(table)
        if count is None:
            errors.append(f"{table}: missing (expected table to exist)")
        elif minimum > 0 and count < minimum:
            errors.append(f"{table}: {count} rows (expected at least {minimum})")
    return errors
