#!/usr/bin/env bash
# shellcheck shell=bash
# Routed libvirt networks for three compact clusters (L3 between hub and spokes).
# Guests also need MASQUERADE out the hypervisor uplink so agent/release pulls
# (quay.io) work when the lab does not route 192.168.70/71/72.

libvirt_enable_ip_forward() {
  _lv_log "Enabling IPv4 forwarding on the hypervisor..."
  libvirt_ssh sysctl -w net.ipv4.ip_forward=1 >/dev/null
  libvirt_ssh bash -c 'grep -q "^net.ipv4.ip_forward=1" /etc/sysctl.d/99-ramendr-libvirt.conf 2>/dev/null || \
    echo net.ipv4.ip_forward=1 > /etc/sysctl.d/99-ramendr-libvirt.conf'
}

# Default IPv4 uplink (e.g. ens1f3). Override with LIBVIRT_UPLINK_IFACE.
libvirt_uplink_iface() {
  if [[ -n "${LIBVIRT_UPLINK_IFACE:-}" ]]; then
    printf '%s\n' "$LIBVIRT_UPLINK_IFACE"
    return 0
  fi
  libvirt_ssh bash -c "ip -4 route show default 2>/dev/null | awk '{print \$5; exit}'"
}

# NAT guest CIDRs out the uplink so quay.io / mirror.openshift.com are reachable.
# Keeps L3 routing between hub/spoke bridges (SNAT only when leaving via uplink).
libvirt_ensure_masquerade() {
  local uplink
  uplink="$(libvirt_uplink_iface)"
  if [[ -z "$uplink" ]]; then
    _lv_err "Cannot detect default uplink interface (set LIBVIRT_UPLINK_IFACE)."
    return 1
  fi
  _lv_log "Ensuring MASQUERADE for libvirt guest nets out ${uplink}..."

  # shellcheck disable=SC2087
  libvirt_ssh bash -s -- "$uplink" <<'EOS'
set -euo pipefail
uplink="$1"
cidrs=(192.168.70.0/24 192.168.71.0/24 192.168.72.0/24)
bridges=(virbr-rd-hub virbr-rd-pri virbr-rd-sec)

for cidr in "${cidrs[@]}"; do
  if ! iptables -t nat -C POSTROUTING -s "$cidr" -o "$uplink" -j MASQUERADE 2>/dev/null; then
    iptables -t nat -A POSTROUTING -s "$cidr" -o "$uplink" -j MASQUERADE
  fi
done

for br in "${bridges[@]}"; do
  if ! ip link show "$br" >/dev/null 2>&1; then
    continue
  fi
  if ! iptables -C FORWARD -i "$br" -o "$uplink" -j ACCEPT 2>/dev/null; then
    iptables -I FORWARD 1 -i "$br" -o "$uplink" -j ACCEPT
  fi
  if ! iptables -C FORWARD -i "$uplink" -o "$br" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT 2>/dev/null; then
    iptables -I FORWARD 1 -i "$uplink" -o "$br" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
  fi
done

if command -v firewall-cmd >/dev/null && firewall-cmd --state >/dev/null 2>&1; then
  for cidr in "${cidrs[@]}"; do
    firewall-cmd --permanent --direct --add-rule ipv4 nat POSTROUTING 0 \
      -s "$cidr" -o "$uplink" -j MASQUERADE >/dev/null 2>&1 || true
  done
  for br in "${bridges[@]}"; do
    firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 \
      -i "$br" -o "$uplink" -j ACCEPT >/dev/null 2>&1 || true
    firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 \
      -i "$uplink" -o "$br" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT >/dev/null 2>&1 || true
  done
  firewall-cmd --reload >/dev/null 2>&1 || true
fi

if command -v iptables-save >/dev/null; then
  mkdir -p /etc/sysconfig
  {
    echo "# RamenDR libvirt NAT — regenerated by libvirt-provision.sh"
    iptables-save -t nat | grep -E '^-A POSTROUTING -s 192\.168\.7[012]\.0/24 -o .+ -j MASQUERADE' || true
    iptables-save -t filter | grep -E '^-A FORWARD .*-o '"$uplink"'|-i '"$uplink" || true
  } > /etc/sysconfig/iptables.ramendr-libvirt-snippet || true

  cat > /usr/local/sbin/ramendr-libvirt-nat.sh <<SCRIPT
#!/usr/bin/env bash
set -euo pipefail
uplink=\$(ip -4 route show default 2>/dev/null | awk '{print \$5; exit}')
[[ -n "\$uplink" ]] || exit 0
for cidr in 192.168.70.0/24 192.168.71.0/24 192.168.72.0/24; do
  iptables -t nat -C POSTROUTING -s "\$cidr" -o "\$uplink" -j MASQUERADE 2>/dev/null \\
    || iptables -t nat -A POSTROUTING -s "\$cidr" -o "\$uplink" -j MASQUERADE
done
for br in virbr-rd-hub virbr-rd-pri virbr-rd-sec; do
  ip link show "\$br" >/dev/null 2>&1 || continue
  iptables -C FORWARD -i "\$br" -o "\$uplink" -j ACCEPT 2>/dev/null \\
    || iptables -I FORWARD 1 -i "\$br" -o "\$uplink" -j ACCEPT
  iptables -C FORWARD -i "\$uplink" -o "\$br" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT 2>/dev/null \\
    || iptables -I FORWARD 1 -i "\$uplink" -o "\$br" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
done
SCRIPT
  chmod 755 /usr/local/sbin/ramendr-libvirt-nat.sh

  cat > /etc/systemd/system/ramendr-libvirt-nat.service <<'UNIT'
[Unit]
Description=RamenDR libvirt guest MASQUERADE
After=network-online.target libvirtd.service
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/sbin/ramendr-libvirt-nat.sh

[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload
  systemctl enable --now ramendr-libvirt-nat.service >/dev/null 2>&1 || \
    systemctl enable ramendr-libvirt-nat.service >/dev/null 2>&1 || true
fi
EOS
}

# openshift-install and mktemp expect /tmp. Lab HVs have shown /tmp deleted
# (tmpfs/unmount or accidental rm); recreate it before any host-side work.
libvirt_ensure_tmpdir() {
  local work="${LIBVIRT_REMOTE_WORKDIR:-/var/lib/ramendr-libvirt}"
  libvirt_ssh bash -c "mkdir -p /tmp /var/tmp $(printf '%q' "$work") && chmod 1777 /tmp /var/tmp"
}

# Make api/apps names resolvable on the hypervisor (openshift-install wait/gather).
# Libvirt dnsmasq only answers guests; host resolv.conf uses 127.0.0.1 without those records.
libvirt_ensure_host_dns() {
  [[ -n "${BASE_DOMAIN:-}" ]] || return 0
  _lv_log "Ensuring /etc/hosts entries for cluster API/apps on the hypervisor..."
  local cluster domain api_ip ingress_vip
  local work="${LIBVIRT_REMOTE_WORKDIR:-/var/lib/ramendr-libvirt}"
  local block=$'# ramendr-libvirt-dns-begin\n'
  for cluster in "${LIBVIRT_CLUSTERS[@]}"; do
    domain="${cluster}.${BASE_DOMAIN}"
    # api/api-int → rendezvous (.21), not VIP .10 — see libvirt_network_xml.
    api_ip="$(libvirt_node_ip "$cluster" 0)"
    ingress_vip="$(libvirt_ingress_vip "$cluster")"
    block+="${api_ip} api.${domain} api-int.${domain}"$'\n'
    block+="${ingress_vip} console-openshift-console.apps.${domain} oauth-openshift.apps.${domain} vault-vault.apps.${domain}"$'\n'
  done
  block+=$'# ramendr-libvirt-dns-end\n'

  # shellcheck disable=SC2087
  libvirt_ssh bash -s -- "$work" <<EOS
set -euo pipefail
work="\$1"
mkdir -p /tmp /var/tmp "\$work"
chmod 1777 /tmp /var/tmp || true
hosts=/etc/hosts
tmp=\$(mktemp -p "\$work" ramendr-hosts.XXXXXX)
if grep -q ramendr-libvirt-dns-begin "\$hosts" 2>/dev/null; then
  sed '/ramendr-libvirt-dns-begin/,/ramendr-libvirt-dns-end/d' "\$hosts" > "\$tmp"
else
  cp "\$hosts" "\$tmp"
fi
cat >> "\$tmp" <<'EOF'
${block}EOF
chmod 644 "\$tmp"
mv "\$tmp" "\$hosts"
EOS
}

libvirt_firewall_forward() {
  local bridges=() cluster
  for cluster in "${LIBVIRT_CLUSTERS[@]}"; do
    bridges+=("$(libvirt_bridge_name "$cluster")")
  done
  if ! libvirt_ssh command -v firewall-cmd >/dev/null; then
    _lv_warn "firewall-cmd not found; ensure forwarding between ${bridges[*]} is allowed."
    return 0
  fi
  local b
  for b in "${bridges[@]}"; do
    libvirt_ssh firewall-cmd --permanent --zone=trusted --change-interface="$b" >/dev/null 2>&1 || true
  done
  libvirt_ssh firewall-cmd --reload >/dev/null 2>&1 || true
}

# Optional $2=api_ip $3=apps_ip override the initial rendezvous / ingress-VIP
# targets (used when flipping DNS onto disk-booted masters).
# Optional $4=uuid keeps virsh net-define from failing with "already exists".
libvirt_network_xml() {
  local cluster="$1"
  local api_ip="${2:-}" apps_ip="${3:-}" uuid="${4:-}"
  local name bridge gw prefix ingress_vip domain
  name="$(libvirt_network_name "$cluster")"
  bridge="$(libvirt_bridge_name "$cluster")"
  gw="$(libvirt_gateway "$cluster")"
  prefix="$(libvirt_cluster_prefix "$cluster")"
  ingress_vip="$(libvirt_ingress_vip "$cluster")"
  domain="${cluster}.${BASE_DOMAIN}"

  local mac0 mac1 mac2 ip0 ip1 ip2
  mac0="$(libvirt_node_mac "$cluster" 0)"
  mac1="$(libvirt_node_mac "$cluster" 1)"
  mac2="$(libvirt_node_mac "$cluster" 2)"
  ip0="$(libvirt_node_ip "$cluster" 0)"
  ip1="$(libvirt_node_ip "$cluster" 1)"
  ip2="$(libvirt_node_ip "$cluster" 2)"

  # Default: api/api-int → rendezvous (.21), not keepalived VIP (.10). After
  # image write, masters' ignition merges
  # https://api-int.<cluster>.<domain>:22623/config/master — MCS listens on the
  # bootstrap node. Pointing DNS at .10 deadlocks firstboot in initramfs.
  api_ip="${api_ip:-$ip0}"
  apps_ip="${apps_ip:-$ingress_vip}"

  local uuid_xml=""
  if [[ -n "$uuid" ]]; then
    uuid_xml="  <uuid>${uuid}</uuid>"
  fi

  cat <<EOF
<network xmlns:dnsmasq="http://libvirt.org/schemas/network/dnsmasq/1.0">
  <name>${name}</name>
${uuid_xml}
  <forward mode="route"/>
  <bridge name="${bridge}" stp="on" delay="0"/>
  <dns>
    <host ip="${api_ip}">
      <hostname>api.${domain}</hostname>
      <hostname>api-int.${domain}</hostname>
    </host>
    <host ip="${apps_ip}">
      <hostname>console-openshift-console.apps.${domain}</hostname>
      <hostname>oauth-openshift.apps.${domain}</hostname>
      <hostname>canary-openshift-ingress-canary.apps.${domain}</hostname>
      <hostname>vault-vault.apps.${domain}</hostname>
    </host>
  </dns>
  <ip address="${gw}" netmask="255.255.255.0">
    <dhcp>
      <range start="192.168.${prefix}.50" end="192.168.${prefix}.99"/>
      <host mac="${mac0}" name="$(libvirt_vm_name "$cluster" 0)" ip="${ip0}"/>
      <host mac="${mac1}" name="$(libvirt_vm_name "$cluster" 1)" ip="${ip1}"/>
      <host mac="${mac2}" name="$(libvirt_vm_name "$cluster" 2)" ip="${ip2}"/>
    </dhcp>
  </ip>
</network>
EOF
}

libvirt_ensure_network() {
  local cluster="$1"
  local name xml
  name="$(libvirt_network_name "$cluster")"
  xml="$(libvirt_network_xml "$cluster")"
  _lv_log "Ensuring libvirt network $name ($(libvirt_cidr "$cluster"))..."
  # Redefine every run so DNS (api → rendezvous) updates apply to existing nets.
  if libvirt_ssh virsh net-info "$name" >/dev/null 2>&1; then
    libvirt_ssh virsh net-destroy "$name" >/dev/null 2>&1 || true
    libvirt_ssh virsh net-undefine "$name" >/dev/null 2>&1 || true
  fi
  libvirt_ssh bash -c "virsh net-define /dev/stdin" <<<"$xml"
  libvirt_ssh virsh net-autostart "$name" >/dev/null
  libvirt_ssh virsh net-start "$name" >/dev/null 2>&1 || true
}

libvirt_ensure_all_networks() {
  local cluster
  libvirt_ensure_tmpdir
  libvirt_enable_ip_forward
  for cluster in "${LIBVIRT_CLUSTERS[@]}"; do
    libvirt_ensure_network "$cluster"
  done
  libvirt_firewall_forward
  libvirt_ensure_masquerade
  libvirt_ensure_host_dns
}

# Point api/api-int (and apps) at live node IPs in libvirt dnsmasq + HV /etc/hosts.
# platform.none keepalived VIPs (.10/.11) never come up on this libvirt layout.
#
# Do NOT virsh net-destroy (detaches guest taps) and do NOT kill dnsmasq
# (DHCP dies; guests become unreachable). Live dns-host updates go through
# virsh net-update --live, which rewrites addnhosts and signals dnsmasq.
libvirt_point_api_dns() {
  local cluster="$1" api_ip="$2" apps_ip="${3:-}"
  local name domain gw xml cur_api cur_apps uuid
  name="$(libvirt_network_name "$cluster")"
  domain="${cluster}.${BASE_DOMAIN}"
  gw="$(libvirt_gateway "$cluster")"
  apps_ip="${apps_ip:-$api_ip}"

  # Hypervisor /etc/hosts (openshift-install wait-for) — merge this cluster
  # into the shared ramendr block so hub/spoke entries coexist.
  # shellcheck disable=SC2087
  libvirt_ssh bash -s -- "${LIBVIRT_REMOTE_WORKDIR:-/var/lib/ramendr-libvirt}" <<EOS
set -euo pipefail
work="\$1"
mkdir -p /tmp /var/tmp "\$work"
chmod 1777 /tmp /var/tmp || true
hosts=/etc/hosts
tmp=\$(mktemp -p "\$work" ramendr-hosts.XXXXXX)
begin="# ramendr-libvirt-dns-begin"
end="# ramendr-libvirt-dns-end"
if grep -q "\$begin" "\$hosts" 2>/dev/null; then
  # Keep other clusters' lines; drop only this domain's api/apps rows.
  # Use index() (literal substring), not ~ regex: gawk warns on "\\." in
  # strings and unescaped dots in ${domain} would be "any char" anyway.
  awk -v d="${domain}" -v begin="\$begin" -v end="\$end" '
    \$0 == begin {print; inblk=1; next}
    \$0 == end {inblk=0; print; next}
    inblk && (index(\$0, "api." d) || index(\$0, "apps." d)) {next}
    {print}
  ' "\$hosts" > "\$tmp"
  # Insert this cluster's rows just before the end marker.
  awk -v end="\$end" -v a="${api_ip} api.${domain} api-int.${domain}" \
      -v b="${apps_ip} console-openshift-console.apps.${domain} oauth-openshift.apps.${domain} vault-vault.apps.${domain}" '
    \$0 == end {print a; print b}
    {print}
  ' "\$tmp" > "\$tmp.new" && mv "\$tmp.new" "\$tmp"
else
  cp "\$hosts" "\$tmp"
  cat >> "\$tmp" <<EOF
\$begin
${api_ip} api.${domain} api-int.${domain}
${apps_ip} console-openshift-console.apps.${domain} oauth-openshift.apps.${domain} vault-vault.apps.${domain}
\$end
EOF
fi
chmod 644 "\$tmp"
mv "\$tmp" "\$hosts"
EOS

  # Skip when guest dnsmasq already answers the desired IPs.
  cur_api="$(libvirt_ssh dig +short @"$gw" "api.${domain}" 2>/dev/null | head -1 | tr -d '[:space:]' || true)"
  cur_apps="$(libvirt_ssh dig +short @"$gw" "console-openshift-console.apps.${domain}" 2>/dev/null | head -1 | tr -d '[:space:]' || true)"
  if [[ "$cur_api" == "$api_ip" && "$cur_apps" == "$apps_ip" ]]; then
    return 0
  fi

  _lv_log "Pointing api.${domain} at ${api_ip}; apps.${domain} at ${apps_ip} (net-update --live)..."

  uuid="$(libvirt_ssh virsh net-uuid "$name" 2>/dev/null | tr -d '[:space:]' || true)"
  xml="$(libvirt_network_xml "$cluster" "$api_ip" "$apps_ip" "$uuid")"

  # Persist XML for the next full network recreate.
  if ! libvirt_ssh bash -c "virsh net-define /dev/stdin >/dev/null" <<<"$xml"; then
    _lv_warn "net-define failed for ${name} (uuid=${uuid:-none})"
    return 1
  fi

  # Live DNS only via libvirt net-update (rewrites addnhosts + SIGHUP dnsmasq).
  # shellcheck disable=SC2087
  libvirt_ssh bash -s -- "$name" "$api_ip" "$apps_ip" "$domain" <<'EOS'
set -euo pipefail
name="$1" api_ip="$2" apps_ip="$3" domain="$4"

# Strip any leftover address=/apps/ wildcard (overrides host records).
conf="/var/lib/libvirt/dnsmasq/${name}.conf"
if [[ -f "$conf" ]] && grep -q "address=/apps.${domain}/" "$conf"; then
  sed -i "/address=\/apps\.${domain}\//d" "$conf"
fi

api_xml="<host ip='${api_ip}'><hostname>api.${domain}</hostname><hostname>api-int.${domain}</hostname></host>"
apps_xml="<host ip='${apps_ip}'><hostname>console-openshift-console.apps.${domain}</hostname><hostname>oauth-openshift.apps.${domain}</hostname><hostname>canary-openshift-ingress-canary.apps.${domain}</hostname><hostname>vault-vault.apps.${domain}</hostname></host>"

# Delete any existing api/apps host blocks (IP may differ), then add the new ones.
# net-update delete matches on hostname content in practice when we pass the host XML.
while IFS= read -r old_xml; do
  [[ -n "$old_xml" ]] || continue
  virsh net-update "$name" delete dns-host "$old_xml" --live --config >/dev/null 2>&1 || true
done < <(python3 - "$name" "$domain" <<'PY'
import subprocess, sys, re, xml.etree.ElementTree as ET
name, domain = sys.argv[1], sys.argv[2]
raw = subprocess.check_output(["virsh", "net-dumpxml", name], text=True)
# Strip xmlns for easier parsing
raw = re.sub(r'\sxmlns(:\w+)?="[^"]+"', "", raw)
root = ET.fromstring(raw)
dns = root.find("dns")
if dns is None:
    sys.exit(0)
want = {
    f"api.{domain}", f"api-int.{domain}",
    f"console-openshift-console.apps.{domain}",
    f"oauth-openshift.apps.{domain}",
    f"canary-openshift-ingress-canary.apps.{domain}",
    f"vault-vault.apps.{domain}",
}
for host in dns.findall("host"):
    names = {h.text for h in host.findall("hostname") if h.text}
    if names & want:
        ip = host.get("ip", "")
        hn = "".join(f"<hostname>{h.text}</hostname>" for h in host.findall("hostname") if h.text)
        print(f"<host ip='{ip}'>{hn}</host>")
PY
)

# net-update add can fail with "matching field" if delete missed a
# hostname; never abort here — addnhosts + HUP is the live source of truth.
virsh net-update "$name" add-first dns-host "$api_xml" --live --config >/dev/null 2>&1 || true
virsh net-update "$name" add-first dns-host "$apps_xml" --live --config >/dev/null 2>&1 || true

# Always rewrite addnhosts (dnsmasq --addn-hosts). Do this even when
# net-update fails so guest dig cannot lose apps records under set -e.
cat > "/var/lib/libvirt/dnsmasq/${name}.addnhosts" <<EOF
${api_ip} api.${domain} api-int.${domain}
${apps_ip} console-openshift-console.apps.${domain} oauth-openshift.apps.${domain} canary-openshift-ingress-canary.apps.${domain} vault-vault.apps.${domain}
EOF
# SIGHUP so dnsmasq re-reads addn-hosts (safe; does not restart DHCP).
pidfile="/run/libvirt/network/${name}.pid"
if [[ -f "$pidfile" ]]; then
  pid="$(cat "$pidfile" 2>/dev/null || true)"
  if [[ -n "${pid}" ]] && kill -0 "$pid" 2>/dev/null; then
    kill -HUP "$pid" || true
  fi
fi
EOS

  sleep 1
  cur_api="$(libvirt_ssh dig +short @"$gw" "api.${domain}" 2>/dev/null | head -1 | tr -d '[:space:]' || true)"
  cur_apps="$(libvirt_ssh dig +short @"$gw" "console-openshift-console.apps.${domain}" 2>/dev/null | head -1 | tr -d '[:space:]' || true)"
  if [[ "$cur_api" != "$api_ip" || "$cur_apps" != "$apps_ip" ]]; then
    _lv_warn "Guest DNS after net-update: api=${cur_api:-?} (want ${api_ip}), apps=${cur_apps:-?} (want ${apps_ip})"
    return 1
  fi
  _lv_log "Guest DNS ok: api=${cur_api} apps=${cur_apps}"
  return 0
}

# After masters join, point API + apps DNS at disk-booted masters (idx 1/2).
# Never prefer node-0 here: during bootstrap it still serves a temporary :6443
# on the live ISO, and selecting it leaves DNS on rendezvous after bootkube
# tears that API down (wait-for then gets connection refused on .21).
#
# Default: only rewrite DNS when idx 1 or 2 actually answer :6443 (so we do
# not yank api off the live bootstrap API too early). Pass force=1 to point at
# node-1 even when :6443 is not up yet (post tear-down / recovery).
# Pass include_rendezvous=1 after node-0 has disk-booted.
libvirt_point_api_dns_to_masters() {
  local cluster="$1"
  local force=0 include_rendezvous=0
  local arg
  for arg in "${@:2}"; do
    case "$arg" in
      force|force=1) force=1 ;;
      include_rendezvous|include_rendezvous=1) include_rendezvous=1 ;;
    esac
  done

  local idx ip api_ip="" apps_ip=""
  local -a order=(1 2)
  if [[ "$include_rendezvous" == "1" ]]; then
    order+=(0)
  fi
  # Pick API and apps independently. Routers often land on a different master
  # than the one answering :6443; falling back to api_ip when :443 is briefly
  # down leaves apps DNS on a node with connection refused (breaks Vault ESO).
  for idx in "${order[@]}"; do
    ip="$(libvirt_node_ip "$cluster" "$idx")"
    if [[ -z "$api_ip" ]] && libvirt_ssh bash -c "timeout 2 bash -c 'echo >/dev/tcp/${ip}/6443'" >/dev/null 2>&1; then
      api_ip="$ip"
    fi
  done
  for idx in 0 1 2; do
    ip="$(libvirt_node_ip "$cluster" "$idx")"
    if [[ -z "$apps_ip" ]] && libvirt_ssh bash -c "timeout 2 bash -c 'echo >/dev/tcp/${ip}/443'" >/dev/null 2>&1; then
      apps_ip="$ip"
    fi
  done
  if [[ -z "$api_ip" ]]; then
    if [[ "$force" != "1" ]]; then
      return 1
    fi
    _lv_warn "No disk-booted master answered :6443 yet; forcing API DNS to node-1"
    api_ip="$(libvirt_node_ip "$cluster" 1)"
  fi
  if [[ -z "$apps_ip" ]]; then
    apps_ip="$api_ip"
  fi
  libvirt_point_api_dns "$cluster" "$api_ip" "$apps_ip"
}

# Hub ACM import resolves spoke api.<cluster>.<domain> via hub CoreDNS → node
# resolv → hub libvirt dnsmasq. Spoke klusterlets need hub api.* the same way.
# Inject every cluster's api/api-int into every network addnhosts (keep apps +
# image-registry rows from ensure_image_registry_dns).
libvirt_ensure_cross_cluster_api_dns() {
  libvirt_resolve_base_domain || true
  if [[ -z "${BASE_DOMAIN:-}" ]]; then
    _lv_warn "Skipping cross-cluster API DNS: BASE_DOMAIN is empty."
    return 1
  fi
  local cluster domain api_ip lines="" idx ip
  for cluster in "${LIBVIRT_CLUSTERS[@]}"; do
    domain="${cluster}.${BASE_DOMAIN}"
    api_ip="$(awk -v d="api.${domain}" 'index($0, d) {print $1; exit}' \
      <<<"$(libvirt_ssh cat "/var/lib/libvirt/dnsmasq/$(libvirt_network_name "$cluster").addnhosts" 2>/dev/null)" \
      || true)"
    if [[ -z "$api_ip" ]]; then
      for idx in 1 2 0; do
        ip="$(libvirt_node_ip "$cluster" "$idx")"
        if libvirt_ssh bash -c "timeout 1 bash -c 'echo >/dev/tcp/${ip}/6443'" >/dev/null 2>&1; then
          api_ip="$ip"
          break
        fi
      done
      api_ip="${api_ip:-$(libvirt_node_ip "$cluster" 1)}"
    fi
    lines+="${api_ip} api.${domain} api-int.${domain}"$'\n'
  done
  _lv_log "Publishing cross-cluster api/api-int DNS on all ramendr-* networks..."
  # shellcheck disable=SC2087
  libvirt_ssh bash -s -- "$lines" <<'EOS' || true
set -euo pipefail
api_lines="$1"
for f in /var/lib/libvirt/dnsmasq/ramendr-*.addnhosts; do
  [[ -f "$f" ]] || continue
  keep=$(grep -E 'apps\.|image-registry' "$f" || true)
  {
    printf '%s' "$api_lines"
    printf '%s\n' "$keep"
  } | awk 'NF && !seen[$0]++' > "${f}.new"
  mv "${f}.new" "$f"
  net=$(basename "$f" .addnhosts)
  pid=$(pgrep -f "dnsmasq.*${net}" | head -1 || true)
  [[ -n "$pid" ]] && kill -HUP "$pid" || true
done
EOS
  _lv_log "Cross-cluster api/api-int DNS published (BASE_DOMAIN=${BASE_DOMAIN})."
}
